### ISSUE TITLE
Notice: Trying to get property of non-object in /vagrant/wordpress/wp-content/plugins/Co-Authors-Plus/php/class-coauthors-guest-authors.php on line 157

### ISSUE THREAD

**Issue by mauteri** [Automattic/Co-Authors-Plus#291]
Code is assuming guest author even when there are none.

**Comment by castlehouse** [comment]
Looks like this was fixed in https://github.com/Automattic/Co-Authors-Plus/commit/0a19a1238e590a6ef3035edd301f4c11066b101a so should no longer be an issue.

**Comment by paulschreiber** [comment]
Did this fix not make it to the WPCOM/VIP repo? I'm still seeing the warning.

**Comment by stevenslack** [comment]
I am also seeing this notice. Just updated from the VIP repo as well.
